In [19]:
import pandas as pd 
import numpy  as np
from pathlib import Path

In [20]:
# Path to raw JSON 
filename ="markets_last40.json"
PROJECT_ROOT = Path.cwd().parent
raw_file = PROJECT_ROOT / "data" / "raw" / filename

# Load JSON into DataFrame
df = pd.read_json(raw_file)

In [21]:
df = df[['id','symbol','name','current_price','market_cap','total_volume','price_change_percentage_24h']]

Checking for null, duplicate and basic cleaning

In [22]:
df.isna().sum()

id                             0
symbol                         0
name                           0
current_price                  0
market_cap                     0
total_volume                   5
price_change_percentage_24h    1
dtype: int64

In [23]:
df.duplicated().sum()

np.int64(0)

In [24]:
df.describe()

       current_price    market_cap  total_volume  price_change_percentage_24h
count     100.000000  1.000000e+02  9.500000e+01                    99.000000
mean     1064.423528  3.020792e+10  2.759024e+09                    -0.705184
std      8678.677480  1.766346e+11  1.381991e+10                     2.146743
min         0.000002  6.354270e+08  0.000000e+00                    -9.994870
25%         0.216034  1.039092e+09  1.554313e+07                    -1.496510
50%         1.370000  2.101650e+09  8.030798e+07                    -0.534770
75%         4.467500  5.544179e+09  2.365460e+08                     0.256525
max     86380.000000  1.727156e+12  1.120973e+11                    10.056760

In [26]:
df[df['symbol'] == 'btc']

,id,symbol,name,current_price,market_cap,total_volume,price_change_percentage_24h
0,bitcoin,btc,Bitcoin,86380.0,1727155952007,6.895293e+10,-2.75614